### DISCUSSION TITLE
Superscript and font variants

### DISCUSSION THREAD

**Discussion by Dgr4h4m** [retorquere/zotero-better-bibtex#2924] [Q&A] [answered]
Hello, I am using Pandoc to convert .md files to .docx for papers I am writing. I use the lua filter to create live citations in my docx file. However, when I have html font variants in my md footnotes such as `<sup>...</sup>` these do not translate into the footnotes in the docx file after I do the Zotero refresh. Is there a way to preserve these font elements when I use the lua filter?

**Comment by retorquere** [comment]
Can you provide an MWE?

**Reply by Dgr4h4m** [reply]
I am sorry, I am not entirely sure what you are asking for. I apologize, I am new to the GitHub and programming world.

**Reply by Dgr4h4m** [reply]
Here is an example of a footnote I have written in md:

```
[@kooijAltenTextzeugenJesajabuches1981, 113. He argues, "Man kann folglich die Vorlage der LXX Jes nur mit der [Vorlage]{.underline} von Q^a^ vergleichen" ("Consequently, one can only compare the *Vorlage* of LXX with the [*Vorlage*]{.underline} of Q^a^"\; author's translation)]
```

Here is what it looks like when I move it over into .docx without the lua fitler:

```
Kooij, Die Alten Textzeugen des Jesajabuches, 113. He argues, “Man kann folglich die Vorlage der LXX Jes nur mit der Vorlage von Q<sup>a</sup> vergleichen” (“Consequently, one can only compare the Vorlage of LXX with the Vorlage of Q<sup>a</sup>”; author’s translation).  
```

Sorry, the text is not rendering right here, I am attaching a screenshot so you can see it.
<img width="871" alt="Screenshot 2024-08-03 093014" src="https://github.com/user-attachments/assets/6f5552d4-18bf-40fe-827e-3120b7347dbb">
 

Here is what it looks like with the lua filter (before Zotero refresh):

```
<Do Zotero Refresh: [@kooijAltenTextzeugenJesajabuches1981, 113. He argues, "Man kann folglich die Vorlage der LXX Jes nur mit der [Vorlage]{.underline} von Q^a^ vergleichen" ("Consequently, one can only compare the *Vorlage* of LXX with the [*Vorlage*]{.underline} of ^a^"\; author's translation)]>
```

Here is what it looks like with the lua filter after Zotero refresh;

```
Kooij, Die Alten Textzeugen des Jesajabuches, 113. He argues, “Man kann folglich die Vorlage der LXX Jes nur mit der Vorlage von Qa vergleichen” (“Consequently, one can only compare the Vorlage of LXX with the Vorlage of a”; author’s translation).
```

I used the following command in the terminal to transfer the document (I use the full file paths in the command, but have shortened them here):

```
pandoc ....\Documents\Obsidian_Vault\Dissertation\Drafts\Chapter1Draft.md --lua-filter=.....\Local\Pandoc\filters\zotero.lua --from=markdown+hard_line_breaks --reference-doc=....\Local\Pandoc\custom-reference.docx --defaults=....\Obsidian_Vault\pandoc-defaults.yaml  -o ....\Dissertation\underline_test1.docx
```

**Reply by retorquere** [reply]
> I am sorry, I am not entirely sure what you are asking for. I apologize, I am new to the GitHub and programming world.

Sorry -- a Minimal Working Example, a standalone document that I can replicate the behavior with rather than just a snippet of it. I've compiled this **MWE**

```
---
references:
  - id: kooijAltenTextzeugenJesajabuches1981
    title: One-click science marketing
    author:
      - family: Fenner
        given: Martin
    container-title: Nature Materials
    volume: 11
    URL: "https://dx.doi.org/10.1038/nmat3283"
    DOI: 10.1038/nmat3283
    issue: 4
    publisher: Nature Publishing Group
    page: 261-263
    type: article-journal
    issued:
      year: 2012
      month: 3
---
He makes the following claim [@kooijAltenTextzeugenJesajabuches1981, 113. He argues, "Man kann folglich die Vorlage der LXX Jes nur mit der [Vorlage]{.underline} von Q^a^ vergleichen" ("Consequently, one can only compare the *Vorlage* of LXX with the [*Vorlage*]{.underline} of Q^a^"\; author's translation)]
```

using `pandoc -o test.docx --citeproc test.md`, and I don't get footnotes that way.

You can fix the rendering using leading and trailing backticks, like so:

````
```
[@kooijAltenTextzeugenJesajabuches1981, 113. He argues, "Man kann folglich die Vorlage der LXX Jes nur mit der [Vorlage]{.underline} von Q^a^ vergleichen" ("Consequently, one can only compare the *Vorlage* of LXX with the [*Vorlage*]{.underline} of Q^a^"\; author's translation)]
```
````

**Reply by Dgr4h4m** [reply]
I appreciate the help here. Specifically, I am trying to utilize your lua filter so that I can have live Zotero citations in my word document. I am using the filter you designed here: [Zotero filter](https://retorque.re/zotero-better-bibtex/exporting/pandoc/index.html) and I do not get the syntax formatted correctly when I use the lua filter to create live citations.

**Reply by retorquere** [reply]
I understand that. I need a minimal markdown document that replicates the problem. I posted an attempt at such a minimal document (**MWE**) above, but that doesn't get me a docx with footnotes, so this is clearly not representative of your document. I need something that is representative of your document.

**Reply by Dgr4h4m** [reply]
I used the MWE you provided above and then ran the following command

pandoc C...\Untitled4.md --lua-filter=...\Pandoc\filters\zotero.lua --from=markdown+hard_line_breaks --reference-doc=C...Local\Pandoc\custom-reference.docx --defaults=...\Obsidian_Vault\pandoc-defaults.yaml  -o ...\Dissertation\underline_test2.docx


Then I opened the word document, and used "zotero document preferences" instead of zotero refresh and it gave me the following footnote: 
![image](https://github.com/user-attachments/assets/96d626a4-ad21-4105-882a-a22d980b813c)


When I use the zotero refresh it does not give a footnote, but the document preferences does.

**Reply by retorquere** [reply]
I need to run it without the lua filter first so that I can see what you're trying to replicate with live citations. When I run

```
pandoc -o MWE.docx --citeproc MWE.md
```

I don't get footnote citations, so it's unsurprising that running it with the lua filter has no footnotes. I have no access to `pandoc-defaults.yaml` and `custom-reference.docx`, so that can't be part of the MWE. MWE is document + command line, self-contained, that should be runnable on any system and would always return the same results.

If the footnotes part isn't relevant to your case, that's fine, but we need to settle on something self-contained of which we can be pretty sure we're getting the same output. Otherwise I'm working sort of blindfolded.

**Reply by Dgr4h4m** [reply]
Sorry, I understand now. Update the MWE as follows:
```
---
zotero_csl_style: chicago-fullnote-bibliography
references:
  - id: kooijAltenTextzeugenJesajabuches1981
    title: Die Alten Textzeugen
    authors:
      - family: Fenner
        given: Martin
    container-title: Nature Materials
    volume: 11
    URL: "https://dx.doi.org/10.1038/nmat3283"
    DOI: 10.1038/nmat3283
    issue: 4
    publisher: Nature Publishing Group
    page: 261-263
    type: article-journal
    issued:
      year: 2012
      month: 3
---
He makes the following claim [@kooijAltenTextzeugenJesajabuches1981, 113. He argues, "Man kann folglich die Vorlage der LXX Jes nur mit der [Vorlage]{.underline} von Q^a^ vergleichen" ("Consequently, one can only compare the *Vorlage* of LXX with the [*Vorlage*]{.underline} of Q^a^"\; author's translation)]
```
Then with the following code:
```
pandoc -o test.docx --citeproc test.md
```
I get this result:
![image](https://github.com/user-attachments/assets/9ea9a3fa-0bd6-4aaa-8aaf-d50b90c84562)

With the lua filter now: 
```
pandoc -o test.docx --lua-filter zotero.lua test.md
```
I get the following before refresh:
![image](https://github.com/user-attachments/assets/7c6a3b7b-cf4e-4999-8624-4efdf5655927)

And the following after refresh:
![image](https://github.com/user-attachments/assets/943061e0-9e1c-4b0f-acdf-ba43660f40dd)

Note, the citation is different in this last screenshot because I have that citekey associated with a different source in my zotero library, but the specifics of the citation are not important.

For the purpose of this question what is important is not the footnote, but the superscript and underline not coming through when I do a zotero refresh.

**Reply by retorquere** [reply]
Thanks. This may not be easy to do - in trying to find out whether it can be done without reimplementing part of pandoc in the filter.

**Comment by Dgr4h4m** [comment]
I understand now. Thank you for your patience, I apologize for not understanding what you were looking for. By default Pandoc uses a parenthetical citation, so I went here: https://github.com/citation-style-language/styles/blob/master/chicago-fullnote-bibliography.csl and downloaded the raw file. I then used the same document but updated the command prompt: 

```
pandoc C:\Users\dgr4h\OneDrive\Documents\Obsidian_Vault\Untitled4.md --citeproc --csl C:\Users\dgr4h\Downloads\chicago-fullnote-bibliography.csl -o C:\Users\dgr4h\OneDrive\Seminary\Dissertation\underline_test2.docx
```

You will need to update the .csl file to match your download path

This produced the following footnote: 
![image](https://github.com/user-attachments/assets/c294468b-47e3-463d-986e-a6ea14af0efd)

**Reply by retorquere** [reply]
Can you give [this](https://gist.github.com/retorquere/d007551346bd62e8209ce490213a2655) a go?

**Reply by Dgr4h4m** [reply]
Here is the result of this filter: 
![image](https://github.com/user-attachments/assets/b77d27c5-1367-45cf-8700-ec4eb3654f7f)


I also tried the other text alterations from this MWE
```
---
zotero_csl_style: chicago-fullnote-bibliography
references:
  - id: kooijAltenTextzeugenJesajabuches1981
    title: Die Alten Textzeugen
    authors:
      - family: Fenner
        given: Martin
    container-title: Nature Materials
    volume: 11
    URL: "https://dx.doi.org/10.1038/nmat3283"
    DOI: 10.1038/nmat3283
    issue: 4
    publisher: Nature Publishing Group
    page: 261-263
    type: article-journal
    issued:
      year: 2012
      month: 3
---
He makes the following claim [@kooijAltenTextzeugenJesajabuches1981, 113. He argues, "Man kann folglich die Vorlage der LXX Jes nur mit der [Vorlage]{.underline} von Q^a^ vergleichen" ("Consequently, one can only compare the *Vorlage* of LXX with the [*Vorlage*]{.underline} of Q^a^"\; author's translation). This is a further test <span class="underline">Underline</span>, and so is~this~, as is this <span class="smallcaps">Small caps</span>]

```


And I got this result: 
![image](https://github.com/user-attachments/assets/73ba7a46-dbf5-4f79-8087-dbe836f6e7fe)

![image](https://github.com/user-attachments/assets/94e97dc6-a241-4c58-bfb9-61ee5e10a9df)
