### ISSUE TITLE
No endpoint found error when exporting to Pandoc for Juris-M only (Zotero is fine)

### ISSUE THREAD

**Issue by kayaulai** [retorquere/zotero-better-bibtex#1789]
**Support log ID:** BUZPVPK7-euc

**Expected behavior:** Citations are properly exported from  both Juris-M and Zotero

**Actual behavior:**

I received the following bug, but for Juris-M only (Zotero works fine)

could not fetch Zotero items: No endpoint found

@shiraiReduplicationNominalizationTibetoBurman2014 not found

(The message appears regardless of what reference is selected, and I have verified the keys.)

**Comment by retorquere** [comment]
Sorry this escaped my attention so long -- can you send a new log? Logs are only kept for a week.

**Comment by kayaulai** [comment]
Here's a new log: BAWGVZDK-euc

**Comment by retorquere** [comment]
And where do you see this error/what are you doing that seems to evoke the error? There are no errors in your log other than that you are over your storage quota for the Zotero servers.

**Comment by kayaulai** [comment]
It's when running Pandoc with the lua filter; it's not an error with JurisM.

**Comment by retorquere** [comment]
What are you using for yaml header/command line params?

**Comment by retorquere** [comment]
Did you add `client: jurism` to the yaml header?

https://retorque.re/zotero-better-bibtex/exporting/pandoc/#from-markdown-to-zotero-live-citations

**Comment by kayaulai** [comment]
Yes, this is what it looks like (I coped from that page):

```
---
title: "(my title)"
author: Ryan Ka Yau Lai
output:
  word_document: default
  bookdown::word_document2: default
zotero:
  scannable-cite: false # only relevant when your compiling to scannable-cite .odt
  client: jurism # defaults to zotero
  author-in-text: false # when true, enabled fake author-name-only cites by replacing it with the text of the last names of the authors
  csl-style: apa # pre-fill the style
...

```
