### ISSUE TITLE
Using zotero.lua within Rmarkdown to produce a .docx file with live citations

### ISSUE THREAD

**Issue by alexflaris** [retorquere/zotero-better-bibtex#1882]
Hello,

Thank you for the BBT package. I am trying to create a .docx from R markdown with live citations. I found the zotero.lua filter at this address (https://retorque.re/zotero-better-bibtex/exporting/pandoc/). I tried knitting my Rmd file, however it seems that there is no connection to Zotero when I am doing that.

I have zotero.lua in my working directory, Zotero (version 5.0.96.2) is up and running while I am knitting the document thru Rstudio (version 1.3.1073) in a Windows 10 environment. I am using the latest version of BBT.

As far as I can tell,  the ```zotero:``` variables of my YAML header are not being picked up since for every reference in my document I am getting the following error in the Rmarkdown console:

```
pandoc-citeproc: reference bagnallSystematicReviewEnhanced2014 not found
```

Here is my YAML header:

```
---
title: "How to create live citations from Rmarkdown"
output:
  bookdown::word_document2:
    reference_docx: ./my_document_style.docx
    pandoc_args: ["--lua-filter=./zotero.lua"]
zotero:
  library: "My Library" #my references are inside a subcollection inside My Library
  scannable-cite: false # only relevant when you're compiling to scannable-cite .odt
  client: zotero
  author-in-text: false # when true, enabled fake author-name-only cites by replacing it with the text of the last names of the authors
  csl-style: jama
---
```
And here is the beginning of my text with a few citations

```
This paper needs live citations [@bagnallSystematicReviewEnhanced2014; @estebanMulticentreComparisonFast2014; @forsmoComplianceEnhancedRecovery2016]. Several studies have shown that this is possible [@couchResponseGashEnhanced2013; @gashEnhancedRecoveryLaparoscopic2012].
```

Of note, I insert the citations with the `rbbt` plugin.

Is there something that I need to change in the YAML header so that citations be picked up?

Thank you,
Alex

Support log ID:
