### ISSUE TITLE
Debugging translator issue for PhD Dissertation type

### ISSUE THREAD

**Issue by resistor4u** [retorquere/zotero-better-bibtex#1950]
I'm using `Thesis` in Zotero's `Item Type` field for all my PhD Dissertations, and `PhD Dissertation` (no punctuation) in the `Type`. Using either pandoc or knitr, the refs cited entry shows as `{{PhD Dissertation}}`. Changing the entry in Zotero and the biblio.bib file to `dissertation`, `Ph.D. Dissertation`, or any other variant produces similar results. My expectation is that, minimally, the entry would not be bounded in `{}` but would appear as whatever the citation style requires, e.g., `Ph.D. Dissertation`, `PhD Dissertation`, `Doctoral Dissertation`, or whatever. When BBT translators are updated in Zotero, sometimes the problem goes away and some updates bring it back. So, I'm guessing the issue is with BBT translators, but maybe also with the `csl` stylesheets (if any are given).

The bibtex manual specifies `@phdthesis` as a particular type, so the question is: How should the entry be recorded in Zotero or what can be done to restore some consistency to how Ph.D.'s appear in refs section?

Here's the support log ID, but not sure it's relevant: 9GVBD9ZB-refs-euc

Paste the following into test.md and test.bib for an MRE:

```
---
title: "My dissertation"
bibliography: "./test.bib"
biblio-style: apalike
listoffigures: True
numbersections: True
reference-section-title: References
output:
  officedown::rdocx_document:
    reference_docx: ../../../reference.docx
    md_extensions: +footnotes+table_captions+multiline_tables+escaped_line_breaks
---

# First section

Test reference, according to Woodson [-@woodsonToutMounnSe1990].
```
and for the test.bib:

```
@phdthesis{woodsonToutMounnSe1990,
  type = {Dissertation},
  title = {Tout {{Mounn S\'e Mounn}}, {{Men Tout Mounn Pa Menm}}: Microlevel {{Sociocultural Aspects}} of {{Land Tenure}} in a {{Northern Haitian Locality}}},
  author = {Woodson, Drexel G.},
  year = {1990},
  address = {{Chicago, IL}},
  school = {Department of Anthropology, The University of Chicago},
  keywords = {ethnography,Haiti,land tenure,peasants}
}
```
