### ISSUE TITLE
.bib to .yaml (via pandoc) gets not imported in zotero (but with end-dots and edited issued-field)

### ISSUE THREAD

**Issue by maybegeek** [retorquere/zotero-better-bibtex#2168]
Hello,

sample bib (`test.bib`):

```
@book{uk:2021:st,
  author     = {Kaunzner, Ulrike A.},
  year       = {2021},
  title      = {Die Stimme als Zeitzeugin. Werberhetorik im Hörfunk},
  address    = {Tübingen},
  publisher  = {Narr Francke Attempto},
}
```
can be imported in Zotero.

via `pandoc test.bib -f biblatex -s -t markdown -o test.yaml` 

(forgot the `-s` / `--standalone` edited after following comment, so the output is non-empty : ) )

I get:

```
---
nocite: "[@*]"
references:
- author:
  - family: Kaunzner
    given: Ulrike A.
  id: "uk:2021:st"
  issued: 2021
  publisher: Narr Francke Attempto
  publisher-place: Tübingen
  title: Die Stimme als Zeitzeugin. Werberhetorik im Hörfunk
  type: book
---
```

which I cannot import by clipboard-copy-paste.

changing the ending dashes to three dots is not enough either.

changing the dashes to dots and changing the issued thing to 

```
---
nocite: "[@*]"
references:
- author:
  - family: Kaunzner
    given: Ulrike A.
  id: "uk:2021:st"
  issued:
  - year: 2021
  publisher: Narr Francke Attempto
  publisher-place: Tübingen
  title: Die Stimme als Zeitzeugin. Werberhetorik im Hörfunk
  type: book
...
```
is importable by copy and paste in zotero.

But is this the recommended way?

using: `Better BibTex Version 6.7.1`

[A34THV4N-euc.tar.gz](https://github.com/retorquere/zotero-better-bibtex/files/8800323/A34THV4N-euc.tar.gz)

thanks,
christoph

**Comment by retorquere** [comment]
When I execute `pandoc test.bib -f biblatex -t markdown -o test.yaml` with that `test.bib`, I get an empty file.

What do you get when `test.bib` is 

```
@book{uk:2021:st,
  author     = {Kaunzner, Ulrike A.},
  year       = {2021},
  month = feb,
  title      = {Die Stimme als Zeitzeugin. Werberhetorik im Hörfunk},
  address    = {Tübingen},
  publisher  = {Narr Francke Attempto},
}
```

**Comment by maybegeek** [comment]
@retorquere 

thanks!

adding the `02` results in:

```
---
nocite: "[@*]"
references:
- author:
  - family: Kaunzner
    given: Ulrike A.
  id: "uk:2021:st"
  issued: 2021-02
  publisher: Narr Francke Attempto
  publisher-place: Tübingen
  title: Die Stimme als Zeitzeugin. Werberhetorik im Hörfunk
  type: book
---
```

your fix in the `test build 6.7.1.2661` fixes the import end-dashes included! thank you : )
