### ISSUE TITLE
.yaml `id` as (optional) `citation-key` on import?

### ISSUE THREAD

**Issue by maybegeek** [retorquere/zotero-better-bibtex#2171]
Hi,

(as this is a general question I did not attach a support log)

Is there a way to use the `id` field in a pandoc converted yaml file (from biblatex) as the (optional) citation-key on Zotero/BBT import?

(bib)

```
@book{uk:2021:st,
  author     = {Kaunzner, Ulrike A.},
  year       = {2021},
  title      = {Die Stimme als Zeitzeugin. Werberhetorik im Hörfunk},
  address    = {Tübingen},
  publisher  = {Narr Francke Attempto},
}
```

(yaml)

```
---
references:
- author:
  - family: Kaunzner
    given: Ulrike A.
  id: "uk:2021:st"
  issued: 2021
  publisher: Narr Francke Attempto
  publisher-place: Tübingen
  title: Die Stimme als Zeitzeugin. Werberhetorik im Hörfunk
  type: book
---
```

thanks!
