### ISSUE TITLE
can we be less strict on blank lines after ending-dashes in .yaml import?

### ISSUE THREAD

**Issue by maybegeek** [retorquere/zotero-better-bibtex#2172]
Hi,

with no blank line after the ending-dashes, as well as with one blank line after the `yaml`-ending-dashes all gets imported properly.

With more than one blank line after the ending-dashes the reference(es) do not get imported:

zero:

```
---
references:
- author:
  - family: Dampf
    given: Hans
  id: "dh:2022:a"
  issued: 2021
  publisher: Verlag-Verlag
  publisher-place: Orthausen
  title: no blank line
  type: book
---
```

one:

```
---
references:
- author:
  - family: Dampf
    given: Hans
  id: "dh:2022:b"
  issued: 2021
  publisher: Verlag-Verlag
  publisher-place: Orthausen
  title: one blank line
  type: book
---

```

two (more than one):

```
---
references:
- author:
  - family: Dampf
    given: Hans
  id: "dh:2022:c"
  issued: 2021
  publisher: Verlag-Verlag
  publisher-place: Orthausen
  title: two blank lines
  type: book
---


```

support log: F69CFDPD-euc

### why is this a problem?

* Browser copy and paste does not always show, that there are more blank lines for the user
* if only blank lines follow it is not evidently clear to the user, that this is not robust
* .yaml-file in github repo, using raw, copy pasting in browser (ff) adds one line to already present autocrlf (in my scenario)

thanks again for your time in clearing up yaml-import or my misunderstandings : )
