### ISSUE TITLE
Comma in suffix after exporting from .md to .odt with Pandoc and zotero.lua

### ISSUE THREAD

**Issue by netgrims** [retorquere/zotero-better-bibtex#2282]
I've been using the zotero.lua filter (3e2046c) with Pandoc (2.18) to export .md files to .odt.

When I export citations with page numbers in them from .md to .odt, the citations get a comma in the suffix for some reason. So a citation that was originally this "[@bergmann.etal_2010, p. 3]" ends up looking like this:

![image](https://user-images.githubusercontent.com/89035122/196923785-23e05bac-da85-4bc2-873a-487efbb2ad7d.png)

This only happens to citations with page numbers. The others all look fine.

The YAML header in the .md document currently looks like this:
```
title: [title]
zotero:
  library: My Library
  scannable-cite: false
  client: zotero
  author-in-text: true
  csl-style: apa
```

Debug log ID: 3PJPKT6V-euc

Any idea what could be causing that?
