### ISSUE TITLE
[Feature]: Using zotero.lua with Quarto/qmd in RStudio

### ISSUE THREAD

**Issue by kang0410** [retorquere/zotero-better-bibtex#2497]
Hi, love your work which has worked well with pandoc on md documents through terminal.
I've been learning to use qmd/Quarto documents as part of my PhD research as I hope to learn both R & Python.
I was following a similar topic about using zotero.lua on RMarkdown documents. https://github.com/retorquere/zotero-better-bibtex/issues/1882
Is something similar possible for Quarto documents? Ideally just being able to hit "render" on RStudio with qmd documents to use zotero.lua somehow and produce a docx that has live zotero citations.
I've tried adapting @alexflaris & @retorquere yaml headers in the qmd document as below, though no luck in producing live zotero citations

```
---
title: "testing"
format: docx
output:
  bookdown::word_document2:
    pandoc_args: ["--lua-/Users/matthewkang/Downloads/zotero.lua"]
zotero:
  library: "/Users/matthewkang/Zotero/citekeys_My_Library.bib" 
  client: zotero
editor: visual
---
``` 

Thank you in advance.

**Comment by retorquere** [comment]
I'm not familiar with how quarto works but it looks like pandoc isn't being ran on compile, and the Lua filter only works in pandoc.

**Comment by kang0410** [comment]
Thank you for the timely response @retorquere
My basic understanding of quarto is that it uses knitr and pandoc, with capacity to incorporate custom Lua filters. 
Had a little more progress with the yaml fields below rendered in RStudio

```
---
title: "rmd_test"
output: 
  word_document:
    pandoc_args: ["--lua-filter=/Users/matthewkang/Downloads/zotero.lua"]
date: "2023-04-25"
zotero:
  client: zotero
  csl-style: apa
  author-in-text: false # when true, enabled fake author-name-only cites by replacing it with the text of the last names of the authors
  scannable-cite: false # only relevant when you're compiling to scannable-cite .odt
bibliography: "/Users/matthewkang/Zotero/MyLib.bib" 
---
``` 
But getting this error, which I presume is the custom zotero.lua & the main quarto lua filters conflicting.

zotero-live-citations f47be20
Error running filter /Applications/quarto/share/filters/main.lua:
/Users/matthewkang/Downloads/zotero.lua:81: attempt to index a nil value (global '_G')
stack traceback:
	[C]: in upvalue 'orig_require'
	[string "..."]:1353: in function 'require'
	/Users/matthewkang/Downloads/zotero.lua:1731: in local 'chunk'
	/Applications/quarto/share/filters/main.lua:4073: in local 'callback'
	[string "..."]:1789: in function <[string "..."]:1787>
	(...tail calls...)
	/Applications/quarto/share/filters/main.lua:368: in function 'make_wrapped_user_filters'
	/Applications/quarto/share/filters/main.lua:15357: in main chunk

Putting this out there to see if there's anyone else using qmd who've managed to incorporate your lua filter in their document rendering. For now, I'll stick with RMarkdown!
