### ISSUE TITLE
Quotes around last names should be removed from citekeys

### ISSUE THREAD

**Issue by njbart** [retorquere/zotero-better-bibtex#856]
With [`"de la Mare"`][`Walter`] in Zotero’s author field, BBT exports the following to CSL JSON, CSL YAML, and biblatex:

```
[
  {
    "id": "\"delamare\":2012",
    "type": "webpage",
    "author": [{ "family": "de la Mare", "given": "Walter" }],
  }
]
```

```
- id: '"delamare":2012'
  type: webpage
  author:
    - family: de la Mare
      given: Walter
```

```
@online{"delamare":2012,
  author = {{de la Mare}, Walter}
}
```

BBT, quite correctly, removes quotes from the last name fields, but they should be removed from the citekeys, too. In the case of biblatex, pandoc-citeproc throws an error if citekeys contain quotes.
